packages:
    - 'packages/core'
    - 'packages/abstract'
    - 'packages/runtime'
    - 'packages/transformer'
    - 'tests/'
    - 'dev/hookyns/1'
    - 'dev/hookyns/2'
    - 'dev-packages/pkg1'
    - 'dev-packages/pkg2-mjs'