packages:
    - 'packages/core'
    - 'packages/rttist'
#    - 'packages/runtime' TODO: This is new thin tst-reflect on top of Rttist
    - 'packages/typegen'
    - 'packages/plugins/vite'
#    - 'packages/plugins/swc'
    - 'tests/'
    - 'dev/mvc-framework'
    - 'dev/hookyns/2'
    - 'dev/hookyns/webpack'
#    - 'dev-packages/pkg1'
#    - 'dev-packages/pkg2-mjs'