packages:
  - packages/core
  - packages/rttist
  - packages/typegen
#  - packages/plugins/rust/crates/rttist-ts-loader
#  - packages/plugins/rust/crates/rttist-ts-loader-wasm
  - packages/plugins/rttist-ts-loader-wasm-built
  - packages/plugins/esbuild-plugin-rttist
#  - packages/plugins/vite-plugin-rttist
  - packages/plugins/vite6-plugin-rttist
#  - packages/plugins/webpack-plugin-rttist
  - packages/plugins/node
  - dev/mvc-framework
  - dev/dts
  - dev/hookyns/2
  - dev/hookyns/webpack
  - dev/wasm/esbuild
#  - dev/wasm/swc
#  - dev/wasm/vite
  - dev/wasm/vite5
  - dev/wasm/vite6
#  - dev/create-react-app
ignoredBuiltDependencies:
  - wasm-pack
