export const PROTOTYPE_TYPE_PROPERTY = "[[type]]";
export const PROTOTYPE_TYPE_INSTANCE_PROPERTY = "[[$type]]";
export const CALLSITE_TYPE_ARGS_PROPERTY = "[[csTArgs]]";
export const CALLSITE_ARGS_TYPE_PROPERTY = "[[csArgsT]]";

export const ModuleIds = {
	Native: "::native",
	Dynamic: "::dynamic",
	Invalid: "::invalid",
	RttistType: "@rttist/dist/Type",
	RttistModule: "@rttist/dist/Module",
} as const;

export const TypeIds = {
	Invalid: `${ModuleIds.Invalid}::Invalid`,

	NonPrimitiveObject: "#object",
	Function: "#Function",
	Any: "#any",
	Unknown: "#unknown",
	Void: "#void",
	Never: "#never",
	Null: "#null",
	Undefined: "#undefined",
	Intrinsic: "#intrinsic",
	String: "#String",
	Number: "#Number",
	BigInt: "#BigInt",
	Boolean: "#Boolean",
	True: "#true",
	False: "#false",
	Date: "#Date",
	Error: "#Error",
	Symbol: "#Symbol",
	UniqueSymbol: "#UniqueSymbol",
	RegExp: "#RegExp",
	Int8Array: "#Int8Array",
	Uint8Array: "#Uint8Array",
	Uint8ClampedArray: "#Uint8ClampedArray",
	Int16Array: "#Int16Array",
	Uint16Array: "#Uint16Array",
	Int32Array: "#Int32Array",
	Uint32Array: "#Uint32Array",
	Float32Array: "#Float32Array",
	Float64Array: "#Float64Array",
	BigInt64Array: "#BigInt64Array",
	BigUint64Array: "#BigUint64Array",
	ArrayDefinition: "#Array",
	TupleDefinition: "#Tuple",
	ReadonlyArrayDefinition: "#ReadonlyArray",
	MapDefinition: "#Map",
	WeakMapDefinition: "#WeakMap",
	SetDefinition: "#Set",
	WeakSetDefinition: "#WeakSet",
	PromiseDefinition: "#Promise",
	GeneratorDefinition: "#Generator",
	AsyncGeneratorDefinition: "#AsyncGenerator",
	IteratorDefinition: "#Iterator",
	IterableDefinition: "#Iterable",
	IterableIteratorDefinition: "#IterableIterator",
	AsyncIteratorDefinition: "#AsyncIterator",
	AsyncIterableDefinition: "#AsyncIterable",
	AsyncIterableIteratorDefinition: "#AsyncIterableIterator",
	ArrayBuffer: "#ArrayBuffer",
	SharedArrayBuffer: "#SharedArrayBuffer",
	Atomics: "#Atomics",
	DataView: "#DataView",
} as const;
