/*
* This file is generated automatically by the RTTIST TypeGen tool.
* Do not edit it manually.
*/
import { ModuleImporter, MetadataLibrary, createGetTypeFunction } from "rttist";

// @ts-ignore; configure this as an external dependency
import { Metadata as InternalMetadataLibrary } from "./internal.typelib";

ModuleImporter.registerImporters({
	"@tst-reflect-transformer/consts": () => import("./consts.js"),
	"@tst-reflect-transformer/index": () => import("./index.js"),
	"@tst-reflect-transformer/ast-utils/createCallsiteCallExpression": () => import("./ast-utils/createCallsiteCallExpression.js"),
	"@tst-reflect-transformer/ast-utils/createCallsiteTypeArgumentsReadVariableStatement": () => import("./ast-utils/createCallsiteTypeArgumentsReadVariableStatement.js"),
	"@tst-reflect-transformer/ast-utils/createConstructGenericClassExpression": () => import("./ast-utils/createConstructGenericClassExpression.js"),
	"@tst-reflect-transformer/ast-utils/createImport": () => import("./ast-utils/createImport.js"),
	"@tst-reflect-transformer/ast-utils/createReferenceExpressions": () => import("./ast-utils/createReferenceExpressions.js"),
	"@tst-reflect-transformer/ast-utils/getArgumentsTypes": () => import("./ast-utils/getArgumentsTypes.js"),
	"@tst-reflect-transformer/ast-utils/getTypeArgumentsInfo": () => import("./ast-utils/getTypeArgumentsInfo.js"),
	"@tst-reflect-transformer/ast-utils/getTypeParametersMap": () => import("./ast-utils/getTypeParametersMap.js"),
	"@tst-reflect-transformer/ast-utils/inferTypeArguments": () => import("./ast-utils/inferTypeArguments.js"),
	"@tst-reflect-transformer/contexts/Context": () => import("./contexts/Context.js"),
	"@tst-reflect-transformer/contexts/TransformerContext": () => import("./contexts/TransformerContext.js"),
	"@tst-reflect-transformer/contexts/TypeContext": () => import("./contexts/TypeContext.js"),
	"@tst-reflect-transformer/config/Config": () => import("./config/Config.js"),
	"@tst-reflect-transformer/config/ConfigReflectionSection": () => import("./config/ConfigReflectionSection.js"),
	"@tst-reflect-transformer/config/getPackageInfo": () => import("./config/getPackageInfo.js"),
	"@tst-reflect-transformer/declarations/callsites": () => import("./declarations/callsites.js"),
	"@tst-reflect-transformer/declarations/ClassContextTypeReference": () => import("./declarations/ClassContextTypeReference.js"),
	"@tst-reflect-transformer/declarations/ClassTypeReference": () => import("./declarations/ClassTypeReference.js"),
	"@tst-reflect-transformer/declarations/ContextTypeReference": () => import("./declarations/ContextTypeReference.js"),
	"@tst-reflect-transformer/declarations/EmitType": () => import("./declarations/EmitType.js"),
	"@tst-reflect-transformer/declarations/general": () => import("./declarations/general.js"),
	"@tst-reflect-transformer/declarations/index": () => import("./declarations/index.js"),
	"@tst-reflect-transformer/declarations/mappers": () => import("./declarations/mappers.js"),
	"@tst-reflect-transformer/declarations/TransformerTypeReference": () => import("./declarations/TransformerTypeReference.js"),
	"@tst-reflect-transformer/declarations/TypeProperties": () => import("./declarations/TypeProperties.js"),
	"@tst-reflect-transformer/dependencies/DependencyInfo": () => import("./dependencies/DependencyInfo.js"),
	"@tst-reflect-transformer/dependencies/DependencyManager": () => import("./dependencies/DependencyManager.js"),
	"@tst-reflect-transformer/dependencies/TypeIndex": () => import("./dependencies/TypeIndex.js"),
	"@tst-reflect-transformer/expression-utils/createAccessToGenericParameter": () => import("./expression-utils/createAccessToGenericParameter.js"),
	"@tst-reflect-transformer/logging/index": () => import("./logging/index.js"),
	"@tst-reflect-transformer/logging/LogColor": () => import("./logging/LogColor.js"),
	"@tst-reflect-transformer/logging/Logger": () => import("./logging/Logger.js"),
	"@tst-reflect-transformer/logging/LogLevel": () => import("./logging/LogLevel.js"),
	"@tst-reflect-transformer/metadata/defaultCreateModuleRegistrars": () => import("./metadata/defaultCreateModuleRegistrars.js"),
	"@tst-reflect-transformer/metadata/MetadataFilesEmitter": () => import("./metadata/MetadataFilesEmitter.js"),
	"@tst-reflect-transformer/metadata/MetadataLibrary": () => import("./metadata/MetadataLibrary.js"),
	"@tst-reflect-transformer/metadata/MetadataManager": () => import("./metadata/MetadataManager.js"),
	"@tst-reflect-transformer/metadata/MetadataNodeFactory": () => import("./metadata/MetadataNodeFactory.js"),
	"@tst-reflect-transformer/metadata/ModuleMetadata": () => import("./metadata/ModuleMetadata.js"),
	"@tst-reflect-transformer/metadata/SourceFileMetadataUpdater": () => import("./metadata/SourceFileMetadataUpdater.js"),
	"@tst-reflect-transformer/plugins/DefaultPlugin": () => import("./plugins/DefaultPlugin.js"),
	"@tst-reflect-transformer/plugins/index": () => import("./plugins/index.js"),
	"@tst-reflect-transformer/plugins/MetadataContext": () => import("./plugins/MetadataContext.js"),
	"@tst-reflect-transformer/plugins/Plugin": () => import("./plugins/Plugin.js"),
	"@tst-reflect-transformer/properties/getCallExpressionArguments": () => import("./properties/getCallExpressionArguments.js"),
	"@tst-reflect-transformer/properties/getCallSignatures": () => import("./properties/getCallSignatures.js"),
	"@tst-reflect-transformer/properties/getComplexNativeTypeRef": () => import("./properties/getComplexNativeTypeRef.js"),
	"@tst-reflect-transformer/properties/getConstantValue": () => import("./properties/getConstantValue.js"),
	"@tst-reflect-transformer/properties/getConstructors": () => import("./properties/getConstructors.js"),
	"@tst-reflect-transformer/properties/getDecoratorProperties": () => import("./properties/getDecoratorProperties.js"),
	"@tst-reflect-transformer/properties/getDecoratorsProperties": () => import("./properties/getDecoratorsProperties.js"),
	"@tst-reflect-transformer/properties/getLiteralProperties": () => import("./properties/getLiteralProperties.js"),
	"@tst-reflect-transformer/properties/getLiteralTypeReference": () => import("./properties/getLiteralTypeReference.js"),
	"@tst-reflect-transformer/properties/getMemberName": () => import("./properties/getMemberName.js"),
	"@tst-reflect-transformer/properties/getPrimitiveTypeReference": () => import("./properties/getPrimitiveTypeReference.js"),
	"@tst-reflect-transformer/properties/getSignatureParametersProperties": () => import("./properties/getSignatureParametersProperties.js"),
	"@tst-reflect-transformer/properties/getTypeParameterProperties": () => import("./properties/getTypeParameterProperties.js"),
	"@tst-reflect-transformer/properties/getTypeProperties": () => import("./properties/getTypeProperties.js"),
	"@tst-reflect-transformer/properties/getWellKnownTypeRef": () => import("./properties/getWellKnownTypeRef.js"),
	"@tst-reflect-transformer/properties/mapIndexes": () => import("./properties/mapIndexes.js"),
	"@tst-reflect-transformer/properties/mapMethods": () => import("./properties/mapMethods.js"),
	"@tst-reflect-transformer/properties/mapProperties": () => import("./properties/mapProperties.js"),
	"@tst-reflect-transformer/serializers/baseTypeSerializer": () => import("./serializers/baseTypeSerializer.js"),
	"@tst-reflect-transformer/serializers/index": () => import("./serializers/index.js"),
	"@tst-reflect-transformer/serializers/serializeTypeReference": () => import("./serializers/serializeTypeReference.js"),
	"@tst-reflect-transformer/serializers/typeKindOnlyTypeSerializer": () => import("./serializers/typeKindOnlyTypeSerializer.js"),
	"@tst-reflect-transformer/tracers/getNodeLocationText": () => import("./tracers/getNodeLocationText.js"),
	"@tst-reflect-transformer/tracers/getTypeSourceLocationText": () => import("./tracers/getTypeSourceLocationText.js"),
	"@tst-reflect-transformer/tracers/printSymbolFlags": () => import("./tracers/printSymbolFlags.js"),
	"@tst-reflect-transformer/tracers/printTypeDebugInfo": () => import("./tracers/printTypeDebugInfo.js"),
	"@tst-reflect-transformer/tracers/printTypeFlags": () => import("./tracers/printTypeFlags.js"),
	"@tst-reflect-transformer/transformers/processDecorator": () => import("./transformers/processDecorator.js"),
	"@tst-reflect-transformer/transformers/processGenericCallExpression": () => import("./transformers/processGenericCallExpression.js"),
	"@tst-reflect-transformer/transformers/updateCallExpression": () => import("./transformers/updateCallExpression.js"),
	"@tst-reflect-transformer/transformers/updateGetTypeCallExpression": () => import("./transformers/updateGetTypeCallExpression.js"),
	"@tst-reflect-transformer/transformers/updateSourceFile": () => import("./transformers/updateSourceFile.js"),
	"@tst-reflect-transformer/types/BaseType": () => import("./types/BaseType.js"),
	"@tst-reflect-transformer/types/ClassType": () => import("./types/ClassType.js"),
	"@tst-reflect-transformer/types/encodeString": () => import("./types/encodeString.js"),
	"@tst-reflect-transformer/utils/canIncludeSourceFile": () => import("./utils/canIncludeSourceFile.js"),
	"@tst-reflect-transformer/utils/changeExtensionForOutput": () => import("./utils/changeExtensionForOutput.js"),
	"@tst-reflect-transformer/utils/declarationHelpers": () => import("./utils/declarationHelpers.js"),
	"@tst-reflect-transformer/utils/directTypeCallsiteReferenceFactory": () => import("./utils/directTypeCallsiteReferenceFactory.js"),
	"@tst-reflect-transformer/utils/findSourceFile": () => import("./utils/findSourceFile.js"),
	"@tst-reflect-transformer/utils/getDecorators": () => import("./utils/getDecorators.js"),
	"@tst-reflect-transformer/utils/getErrorMessage": () => import("./utils/getErrorMessage.js"),
	"@tst-reflect-transformer/utils/getRelativePath": () => import("./utils/getRelativePath.js"),
	"@tst-reflect-transformer/utils/getSourceFileId": () => import("./utils/getSourceFileId.js"),
	"@tst-reflect-transformer/utils/getTypeNodeIdentifier": () => import("./utils/getTypeNodeIdentifier.js"),
	"@tst-reflect-transformer/utils/getTypeRef": () => import("./utils/getTypeRef.js"),
	"@tst-reflect-transformer/utils/getUniqueSymbolInfo": () => import("./utils/getUniqueSymbolInfo.js"),
	"@tst-reflect-transformer/utils/isExported": () => import("./utils/isExported.js"),
	"@tst-reflect-transformer/utils/isFileExtensionRequired": () => import("./utils/isFileExtensionRequired.js"),
	"@tst-reflect-transformer/utils/isInterestingStatement": () => import("./utils/isInterestingStatement.js"),
	"@tst-reflect-transformer/utils/modifierHelpers": () => import("./utils/modifierHelpers.js"),
	"@tst-reflect-transformer/utils/normalizePath": () => import("./utils/normalizePath.js"),
	"@tst-reflect-transformer/utils/removeExtension": () => import("./utils/removeExtension.js"),
	"@tst-reflect-transformer/utils/symbolHelpers": () => import("./utils/symbolHelpers.js"),
	"@tst-reflect-transformer/utils/toExpression": () => import("./utils/toExpression.js"),
	"@tst-reflect-transformer/utils/typeHelpers": () => import("./utils/typeHelpers.js"),
	"@tst-reflect-transformer/visitors/blockVisitor": () => import("./visitors/blockVisitor.js"),
	"@tst-reflect-transformer/visitors/callExpressionVisitor": () => import("./visitors/callExpressionVisitor.js"),
	"@tst-reflect-transformer/visitors/classVisitor": () => import("./visitors/classVisitor.js"),
	"@tst-reflect-transformer/visitors/constructorVisitor": () => import("./visitors/constructorVisitor.js"),
	"@tst-reflect-transformer/visitors/declarationVisitor": () => import("./visitors/declarationVisitor.js"),
	"@tst-reflect-transformer/visitors/functionVisitor": () => import("./visitors/functionVisitor.js"),
	"@tst-reflect-transformer/visitors/interfaceVisitor": () => import("./visitors/interfaceVisitor.js"),
	"@tst-reflect-transformer/visitors/mainVisitor": () => import("./visitors/mainVisitor.js"),
	"@tst-reflect-transformer/visitors/methodVisitor": () => import("./visitors/methodVisitor.js"),
	"@tst-reflect-transformer/visitors/newExpressionVisitor": () => import("./visitors/newExpressionVisitor.js"),
	"@tst-reflect-transformer/visitors/sourceFileVisitor": () => import("./visitors/sourceFileVisitor.js"),
	"@tst-reflect-transformer/visitors/typeAliasVisitor": () => import("./visitors/typeAliasVisitor.js"),
	"@tst-reflect-transformer/properties/mappers/mapConditional": () => import("./properties/mappers/mapConditional.js"),
	"@tst-reflect-transformer/properties/mappers/mapEnum": () => import("./properties/mappers/mapEnum.js"),
	"@tst-reflect-transformer/properties/mappers/mapEnumLiteral": () => import("./properties/mappers/mapEnumLiteral.js"),
	"@tst-reflect-transformer/properties/mappers/mapFunction": () => import("./properties/mappers/mapFunction.js"),
	"@tst-reflect-transformer/properties/mappers/mapIndex": () => import("./properties/mappers/mapIndex.js"),
	"@tst-reflect-transformer/properties/mappers/mapIndexedAccessType": () => import("./properties/mappers/mapIndexedAccessType.js"),
	"@tst-reflect-transformer/properties/mappers/mapIntersection": () => import("./properties/mappers/mapIntersection.js"),
	"@tst-reflect-transformer/properties/mappers/mapObject": () => import("./properties/mappers/mapObject.js"),
	"@tst-reflect-transformer/properties/mappers/mapObjectLiteral": () => import("./properties/mappers/mapObjectLiteral.js"),
	"@tst-reflect-transformer/properties/mappers/mapStringMapping": () => import("./properties/mappers/mapStringMapping.js"),
	"@tst-reflect-transformer/properties/mappers/mapTemplateLiteral": () => import("./properties/mappers/mapTemplateLiteral.js"),
	"@tst-reflect-transformer/properties/mappers/mapTuple": () => import("./properties/mappers/mapTuple.js"),
	"@tst-reflect-transformer/properties/mappers/mapTypeParameter": () => import("./properties/mappers/mapTypeParameter.js"),
	"@tst-reflect-transformer/properties/mappers/mapUnion": () => import("./properties/mappers/mapUnion.js"),
	"@tst-reflect-transformer/properties/mappers/mapUniqueSymbol": () => import("./properties/mappers/mapUniqueSymbol.js"),
});

export const getType = createGetTypeFunction(InternalMetadataLibrary);

/** @internal */
export const Metadata: MetadataLibrary = InternalMetadataLibrary;