import { Config } from "../lib/config/config";

export type WorkerArguments = {
	// /**
	//  * Name of the file generated by the worker.
	//  */
	// partName: string;

	/**
	 * List of files to process.
	 */
	files: string[];

	/**
	 * Configuration.
	 */
	config: Config;

	// /**
	//  * TypeScript compiler options.
	//  */
	// compilerOptions: CompilerOptions;
};
