pub enum TypeIds {
    Invalid,
    NonPrimitiveObject,
    Function,
    Any,
    Unknown,
    Void,
    Never,
    Null,
    Undefined,
    String,
    Number,
    BigInt,
    Boolean,
    True,
    False,
    Date,
    Error,
    Symbol,
    UniqueSymbol,
    RegExp,
    Int8Array,
    Uint8Array,
    Uint8ClampedArray,
    Int16Array,
    Uint16Array,
    Int32Array,
    Uint32Array,
    Float32Array,
    Float64Array,
    BigInt64Array,
    BigUint64Array,
    ArrayDefinition,
    TupleDefinition,
    ReadonlyArrayDefinition,
    MapDefinition,
    WeakMapDefinition,
    SetDefinition,
    WeakSetDefinition,
    PromiseDefinition,
    GeneratorDefinition,
    AsyncGeneratorDefinition,
    IteratorDefinition,
    IterableDefinition,
    IterableIteratorDefinition,
    AsyncIteratorDefinition,
    AsyncIterableDefinition,
    AsyncIterableIteratorDefinition,
    ArrayBuffer,
    SharedArrayBuffer,
    Atomics,
    DataView,
}

impl TypeIds {
    pub fn to_str(&self) -> &'static str {
        match *self {
            TypeIds::Invalid => "::invalid::Invalid",
            TypeIds::NonPrimitiveObject => "#object",
            TypeIds::Function => "#Function",
            TypeIds::Any => "#any",
            TypeIds::Unknown => "#unknown",
            TypeIds::Void => "#void",
            TypeIds::Never => "#never",
            TypeIds::Null => "#null",
            TypeIds::Undefined => "#undefined",
            TypeIds::String => "#String",
            TypeIds::Number => "#Number",
            TypeIds::BigInt => "#BigInt",
            TypeIds::Boolean => "#Boolean",
            TypeIds::True => "#true",
            TypeIds::False => "#false",
            TypeIds::Date => "#Date",
            TypeIds::Error => "#Error",
            TypeIds::Symbol => "#Symbol",
            TypeIds::UniqueSymbol => "#UniqueSymbol",
            TypeIds::RegExp => "#RegExp",
            TypeIds::Int8Array => "#Int8Array",
            TypeIds::Uint8Array => "#Uint8Array",
            TypeIds::Uint8ClampedArray => "#Uint8ClampedArray",
            TypeIds::Int16Array => "#Int16Array",
            TypeIds::Uint16Array => "#Uint16Array",
            TypeIds::Int32Array => "#Int32Array",
            TypeIds::Uint32Array => "#Uint32Array",
            TypeIds::Float32Array => "#Float32Array",
            TypeIds::Float64Array => "#Float64Array",
            TypeIds::BigInt64Array => "#BigInt64Array",
            TypeIds::BigUint64Array => "#BigUint64Array",
            TypeIds::ArrayDefinition => "#Array",
            TypeIds::TupleDefinition => "#Tuple",
            TypeIds::ReadonlyArrayDefinition => "#ReadonlyArray",
            TypeIds::MapDefinition => "#Map",
            TypeIds::WeakMapDefinition => "#WeakMap",
            TypeIds::SetDefinition => "#Set",
            TypeIds::WeakSetDefinition => "#WeakSet",
            TypeIds::PromiseDefinition => "#Promise",
            TypeIds::GeneratorDefinition => "#Generator",
            TypeIds::AsyncGeneratorDefinition => "#AsyncGenerator",
            TypeIds::IteratorDefinition => "#Iterator",
            TypeIds::IterableDefinition => "#Iterable",
            TypeIds::IterableIteratorDefinition => "#IterableIterator",
            TypeIds::AsyncIteratorDefinition => "#AsyncIterator",
            TypeIds::AsyncIterableDefinition => "#AsyncIterable",
            TypeIds::AsyncIterableIteratorDefinition => "#AsyncIterableIterator",
            TypeIds::ArrayBuffer => "#ArrayBuffer",
            TypeIds::SharedArrayBuffer => "#SharedArrayBuffer",
            TypeIds::Atomics => "#Atomics",
            TypeIds::DataView => "#DataView",
        }
    }

    pub fn to_string(&self) -> String {
        self.to_str().to_string()
    }
}
